// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/home/nstar/ths_HH4b/limitSetting/step1/./drawAlpha2.C";

#endif
